version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependancy-name: "rails"
        update-types: [version-update:semver-major"]
